### ISSUE TITLE
load_map over mqtt is not working

### ISSUE THREAD

**Issue by Thomas55555** [rand256/valetudo#65] opened 2020-01-07 21:14 UTC
Hi,
I'm new here. Hope I'm right.
I'm using 0.8.1 and tried to work with the multi-floor feature. I can store am map and load it in the web Interface of the Mi Robot Vacuum.
The robot (Gen 2) is connected via MQTT to fhem. With fhem I'm able to store a map.
`store_map valetudo/rockrobo/custom_command {"command":"store_map","name":"$EVTPART1"}`
After the command there is a new folder in `/mnt/data/valetudo/maps` with all neccessary files.
But I'm not able to load a map with this command:
`load_map valetudo/rockrobo/custom_command {"command":"load_map","name":"$EVTPART1"}`
`$EVTPART1` is e.g. `oben`
Has anyone an idea what the problem can be?
cheers Thomas

**Comment by rand256** [comment] 2020-01-08 08:01
I'd suggest to check what is written to `/var/log/upstart/valetudo.log` when you send that command.

**Comment by Thomas55555** [comment] 2020-01-08 16:43
I stored a map and it was working again. After that I tried to load a map which was still not working. This was around 17:35. But none of the commands was logged. The last ones were these:
`[35m2020-01-08T16:00:28.712Z[39m Robot connected`
`[35m2020-01-08T16:30:28.712Z[39m Robot connected`
Seems like I also have an problem with the time zone :)

**Comment by nicedevil007** [comment] 2020-01-09 10:45
Hey rand256,,

I don't know if that belongs to the same issue but since a week or something like that I noticed, that my MQTT node in Node-RED stops getting map_data after some minutes of fresh started cleaning.

Then my map looks like this:
![grafik](https://user-images.githubusercontent.com/17103076/72060910-2d70a000-32d5-11ea-945e-96ea43b0919a.png)

If I go to valetudo's own page everything seems fine. The map was drawn completly. I also tested this with Mqtt.fx to verify that it isn't a node-red problem. Also mqtt.fx didn't show any map data after some minutes.

**Comment by Krazy998** [comment] 2020-01-09 20:35
I'm noticing the same issue. I might have mistakenly related it to this issue #64 

Happening with 0.8.1 version. Restarting the robot fixes the problem

**Comment by Krazy998** [comment] 2020-01-09 21:53
OK - i was sitting and watching what actually happens. Hopefully this is helpful.

I put the robot to work. Sitting on a ssh console I noticed the ssh session froze and no commands could be run for about 30 seconds. This is the moment the mqtt maps stopped drawing. 

So it seems like robot is momentarily losing network connectivity and the bot stops sending map data via mqtt when it reconnects.

I then noticed this in the valetudo logs the moment the bot lost network connectivity and the maps stopped updating:

2020-01-09T21:09:06.898Z Robot connected
2020-01-09T21:39:06.897Z Robot connected
**2020-01-09T21:46:37.441Z Connected successfully to mqtt server**
2020-01-09T21:46:37.530Z Robot connected

So maybe we need to look at what has potentially changed in the latest versions of valetudo in regards to how it sends map data via mqtt and its retry behaviour?

**Comment by rand256** [comment] 2020-01-10 16:22
The issue with `load_map` in mqtt is because of missing, well, map reloading code. It only replaced files before and stopped on that. Hopefully I've fixed that today, so it should reload as well. But I don't use mqtt myself and can't actually check if it's really ok now.

As for valetudo stopping publishing maps to mqtt, I'm currently unable to reproduce the issue. I've set up a mosquitto on my server today, connected valetudo to it and send vacuum to 30-min zoned cleaning. Everything works exactly like it should. At least map data was received by mosquitto on regular basis. I didn't parsed it though.

**Comment by Krazy998** [comment] 2020-01-10 19:49
thanks for that. To reproduce it you will need to have the bot lose network connectivity for about 30 seconds - 1 minute. That was a key piece I noted when I was troubleshooting the problem in real time.

Maybe somehow put in a iptables rule on the robot to drop all connectivity to mqtt for 30 seconds and then reallow it? 

Important piece was to see the "Connected successfully to mqtt server" message when the bot recovered its network.

**Comment by Krazy998** [comment] 2020-01-21 10:23
Hey @rand256 Just wanted to  let you know that my issue above has been resolved with 0.8.2! Thank you!

**Closed as completed** 2020-01-22 07:18 UTC

**Comment by nicedevil007** [comment] 2020-01-22 13:54
@rand256 and @Krazy998 same here, problem with not sending mqtt data after some seconds seems to be solved with 0.8.2 <3 great work!
