### ISSUE TITLE
No Wifi on provided pre-built firmware image

### ISSUE THREAD

**Issue by WouterJN** [rand256/valetudo#26] opened 2019-11-03 19:06 UTC
Describe the bug:

After flashing the Valetudo firmware successfully the vacuum does not create a Wifi accesspoint. I tried to hold the reset button for >30 seconds but still no accespoint has been created.

The robot can still clean by pressing the power button

Other Info:
Vacuum Model:  S5
Valetudo Version: V1898

Terminal during flashing:

`INFO:miio.updater:Using local /Users/wouter/Downloads/v1898.fullos.pkg (md5: 355c8df23cf7fd4a564dd1cad51701dd)
Hosting file at http://192.168.8.88:61273/v1898.fullos.pkg
Update started!
  0%|                                                                        | 0/100 [00:00<?, ?it/s]192.168.8.1 - - [03/Nov/2019 19:30:50] "GET /v1898.fullos.pkg HTTP/1.1" 200 -
Downloading:  95%|███████████████████████████████████████████████▌  | 95/100 [03:38<00:10,  2.18s/it]INFO:miio.updater:Got a request, should be downloading now.
Downloading: 100%|█████████████████████████████████████████████████| 100/100 [03:43<00:00,  2.09s/it]Installation started, please wait until the vacuum reboots
Downloading: 100%|█████████████████████████████████████████████████| 100/100 [03:44<00:00,  2.25s/it]
(venv) wouter@Wouters-MacBook-Pro flasher % `

**Comment by commensal** [comment] 2019-11-03 19:52
Same here. Builtin AP is non existent. Had to do factory reset.

**Comment by s3er** [comment] 2019-11-03 21:16
Also no WiFi for me on 1st Gen after flashing 0.4.0-RE5.1 preview. Robot was not connected to WiFi before flashing.

**Comment by rand256** [comment] 2019-11-04 14:32
Well, published firmware images for RE5.1 were made with [forked dustcloud's imagebuilder](https://github.com/rand256/dustcloud) script which had very few changes compared to the [original one](https://github.com/dgiese/dustcloud) (that is known to work well). And, as I could see, none of those changes could possibly break AP mode. So, if it's broken, then probably something is broken in origin imagebuilder and/or stock images themselves.

I myself am using images built for S5 exactly the same way as these (apart of a couple additional features enabled and nothing disabled), and they're working fine for me. But it should be noted: I installed them over the provisioned old firmware, so they just connected to my wireless network using an old settings, without ever entering an AP mode. Also I can say just nothing about Gen1 version since I own only Gen2.

To conclude, releasing prepared firmware images were announced as an experiment. And I wished it'd go well, but seems it didn't. I had no positive reports about these images so far, but three negative reports are right here. Right now I'm unable to debug Wi-Fi issues on the provided images, nor it falls into the scope of Valetudo application at all - as they're in the scope of the firmware.

I definitely don't want to release broken images, so for now I denote this experiment as failed and will from now on make releases of Valetudo app only, as before.

**Comment by rand256** [comment] 2019-11-04 14:36
If anyone has any ideas on this, or had succeeded in running those pre-built images, please post.

**Comment by diabl0w** [comment] 2019-11-12 11:25
I am not sure about the other reporters here, but for my case, the issue is that the vacuum first says "failed updating, reverting to previous firmware" and then after that there is no access point. i tried flashing twice in case there was a corruption that occurred during the transfer. the resolution is to factory reset by holding the plug button while quick pressing the wifi reset button

**Comment by giejay** [comment] 2019-11-17 15:02
I installed the latest prebuilt firmware and it's working fine for me on the v1. I should say, i did not had to enter AP mode because I already have a token.

**Comment by hawkeye223** [comment] 2019-11-18 19:04
You can try the repository - https://github.com/zvldz/vacuum.
Using it, working firmware versions are created. See the link: (http://w3bsit3-dns.com/forum/index.php?showtopic=881982&st=3600#entry82130220
https://vacuumz.info/download/).

**Comment by rand256** [comment] 2019-11-18 19:47
It is ideologically the same as used here.

**Comment by hawkeye223** [comment] 2019-11-19 08:18
> It is ideologically the same as used here.

Yes, but it is finalized and really works!

**Comment by rand256** [comment] 2019-11-19 15:29
> Yes, but it is finalized and really works!

I also have mine "really working" for months without any major issues. But at the time being I can't call _any_ roborock firmware "finalized" including full stock.

Meanwhile, would anyone dare to install this [1886-based image](https://fs.erinome.net/roborock/valetudo/RE7/testing/) containing RE7 to check if it works for them? I remember having "updating failed" on 1898, but it didn't matter since actually it had installed ok regardless of the message. Maybe others aren't so lucky, so lets check how it would go on 1886.

**Comment by diabl0w** [comment] 2019-11-24 10:13
@rand256 I believe in some other forum that you stated firmware versions above 1820 did nit have many cleaning upgrades and most changes to firmware were debugging changes for logging. do you still have these same thoughts? do you think 1820 may be the best version to use then?

**Comment by rand256** [comment] 2019-11-24 10:19
@diabl0w, I said that there were quiet a lot of debug versions above 1820 released at that time. They were never delivered to users via official channels. But afterwards there were released a few official upgrades via mi Home - for example 1864, 1886 and 1898. I don't think there's a reason to stay on 1820 right now.

**Comment by diabl0w** [comment] 2019-11-25 22:52
> @diabl0w, I said that there were quiet a lot of debug versions above 1820 released at that time. They were never delivered to users via official channels. But afterwards there were released a few official upgrades via mi Home - for example 1864, 1886 and 1898. I don't think there's a reason to stay on 1820 right now.

@rand256 thank you for the clarification and update

**Comment by rand256** [comment] 2019-12-01 07:44
This issue should be fixed with RE7.1 release.

**Closed as completed by rand256** 2019-12-01 07:44 UTC
Labels: help wanted
