### ISSUE TITLE
Map reset after few days and language is partly english

### ISSUE THREAD

**Issue by jackydany** [rand256/valetudo#225] opened 2020-05-02 09:15 UTC
After a few days the robot had a overlayed map on the map in the gui.
i have activated lab mode and had a reset for the map and then a complete cleaning. everything was working fine for 3-4 days now.
after these couple of days i realized, there was "another" map over the normal map, and this one was rotated. So i reset the map again and started a new cleaning.
when the robot entered the dock, the map was lost again.
so i reset the map again, disabled lab mode, saved, activated lab mode, saved and started a new cleaning. wont help. map isnt saved.

also, i installed german language pack. now, the robot partly is back to english. for example:
going to dock is back to english, finished zoned cleaning is still german.
i cant tell if its all the time, always the same sounds or if it varies.

**How to Reproduce**

just start cleaning, not zoned cleaning

**Expected behavior**

map should be saved in lab mode to storae zones, otherwise zones get lost and no map is stored.

**Vacuum Model:** Gen2

**Valetudo Version:**  your latest ready build firmware 2008 + valetudo RE 0.9.3

**Comment by pidator** [comment] 2020-05-02 14:57
> after these couple of days i realized, there was "another" map over the normal map, and this one was rotated. 

The error you described is a known error of the roborock firmware and isn't related to valetudo: it occurs when the robot got stuck or if one of the wheels ran free. Then a new map will be build on top of the old one, sometimes rotated too, yes. Try to figure out if something like this happens to your robot.

> also, i installed german language pack. now, the robot partly is back to english. 

You'll need the latest german language pack, because there were some changes/new sounds with 2008. Try perhaps the pack for fw 2008 from [here](https://vacuumz.info/download/voice/s5/2008/).

**Comment by rand256** [comment] 2020-05-02 16:35
I remind that valetudo is in fact a GUI for manufacturer's firmware. It doesn't define how the map is built, it just shows what firmware does. Thus your map issues can't be fixed in valetudo, as these issues aren't valetudo's.

**Comment by jackydany** [comment] 2020-05-02 22:25
ok, thanks.
i know that valetudo is "only" a webinterface, but i thought these issues were related to valetudo.

with the language pack..... it worked a few days, now there are some sounds english again.
the same language pack on the gen1 is fine as well. so i dont think its the pack itself.

is there any way / workaround for the map-thing as this is really annoying :( and i cant define zones as they are different the next walkthrough.

and no, the robot didnt got stuck anywhere inbetween. but i will run some testing tomorrow.

thanks a lot

**Comment by pidator** [comment] 2020-05-02 22:35
> with the language pack..... it worked a few days, now there are some sounds english again.

That's wired, this could only happen by deleting (or loosing) the corresponding sound files on file system... have you thought about a hard factory reset and start again with an clean installation?

> the same language pack on the gen1 is fine as well. so i dont think its the pack itself.

Gen1 and Gen2 language packs are definitely different!! So I would recommend using the pack for Gen2 and if your on fw 2008 using the related pack for this firmware too!

**Comment by Stramm** [comment] 2020-05-03 18:36
A workaround could be to save the map and when you see problems to reload it. Not really pretty, I admit.

**Comment by flyingToast3r** [comment] 2020-05-17 05:49
Even if it is not a problem of valetudo, it seems that it is may caused by the image building process and since @rand256 provides pre-compiled binaries (which is quite nice), the question is not completely unrelated to this project in my opinion. Hypfer point out that there is a experimental bug fix in the dustcould builder. @rand256: can this project somehow benefit from this finding? I have currently no overview about how you build the image.

**Comment by rand256** [comment] 2020-05-17 05:57
This issue wasn't about random factory resets but some weird map reset. So no, applying fixes that would probably prevent random resets on vanilla valetudo won't help with this.

**Comment by flyingToast3r** [comment] 2020-05-17 06:18
ah good point. seems to be too early for me today. It seems I was mixing two threads. Sorry for the confusion.

**Closed as completed** 2020-08-01 15:16 UTC
