### ISSUE TITLE
loosing map after fw reset

### ISSUE THREAD

**Issue by AlexOnFOSS** [rand256/valetudo#129] opened 2020-02-20 05:23 UTC
Hey there,

unfortunately the roborock does sometimes automatically reset its firmware to stock firmware. When i flash it  back to your modified firmware I lose my previously saved maps. 
I would like to backup and restore the maps, the zones, the no-go-areas manually via ssh. I am using the experimental map feature and safe various maps for each level in my house. 
What files do I have to backup and restore to achieve this?

I am using roborock s50 and your image v11_001898.pkg

Ps: As feature request it would be nice to achieve this via the Browser itself.

**Comment by rand256** [comment] 2020-02-20 06:17
Duplicate of #41.

**Closed as completed by rand256** 2020-02-20 06:17 UTC
